### ISSUE TITLE
Fix for Linux build.

### ISSUE THREAD

**Issue by DJs3000** [simple-coding-channel/SimpleEngine#1]
Не смог оформить пул реквест, поэтому напишу тут. При сборке на линуксе словил две ошибки.
1 ошибка:
gcc: "/root/dev/SimpleEngine/SimpleEngineCore/src/SimpleEngineCore/Input.cpp", строка 4: ошибка #20:
          идентификатор "size_t" не определен
      bool Input::m_keys_pressed[static_cast<size_t>(KeyCode::KEY_LAST) + 1] = {};

- фиксится добавлением #include <stdlib.h> в файлик Input.cpp

2 ошибка:
gcc: "/root/dev/SimpleEngine/SimpleEngineCore/src/SimpleEngineCore/Rendering/OpenGL/VertexBuffer.hpp", строка 22: ошибка #20:
          идентификатор "uint32_t" не определен
          uint32_t component_type;

- фиксится добавлением #include <stdint.h> в файлик VertexBuffer.hpp

**Comment by AsuRaHan** [comment]
спасибо! у меня тоже взлетело на линуксе

**Comment by simple-coding-channel** [comment]
Fixed!
